// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAavM03AuWxIrZQKpnmj0LdSt6WuiUhiLc',
    appId: '1:1067298464223:web:3b8c2ebb09433866e9646a',
    messagingSenderId: '1067298464223',
    projectId: 'bukidbayan-capstoners',
    authDomain: 'bukidbayan-capstoners.firebaseapp.com',
    storageBucket: 'bukidbayan-capstoners.firebasestorage.app',
    measurementId: 'G-YBDQ9KTD0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsLae7_9bssgvUxmhOpkx6eW9K2FqIrEU',
    appId: '1:1067298464223:android:33272481e0e2a870e9646a',
    messagingSenderId: '1067298464223',
    projectId: 'bukidbayan-capstoners',
    storageBucket: 'bukidbayan-capstoners.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzd_3ees30agQx9--B5bISfnoPpkAqiK0',
    appId: '1:1067298464223:ios:cf8042ac387939b3e9646a',
    messagingSenderId: '1067298464223',
    projectId: 'bukidbayan-capstoners',
    storageBucket: 'bukidbayan-capstoners.firebasestorage.app',
    iosBundleId: 'com.example.phixlabInventory',
  );
}
